import { AccessToken, AuthorizationCode } from 'simple-oauth2';
import { AuthorizeUrlProps, PardotProps, RawAccessToken, RefreshCallback } from './types';
import Accounts from './objects/accounts';
import { AxiosInstance } from 'axios';
import Campaigns from './objects/campaigns';
import CustomFields from './objects/custom-fields';
import CustomRedirects from './objects/custom-redirects';
import DynamicContent from './objects/dynamic-content';
import EmailClicks from './objects/email-clicks';
import Emails from './objects/emails';
import EmailTemplates from './objects/email-templates';
import Forms from './objects/forms';
import LifecycleHistories from './objects/lifecycle-histories';
import LifecycleStages from './objects/lifecycle-stages';
import ListMemberships from './objects/list-memberships';
import Lists from './objects/lists';
import Opportunities from './objects/opportunities';
import ProspectAccounts from './objects/prospect-accounts';
import Prospects from './objects/prospects';
import TagObjects from './objects/tag-objects';
import Tags from './objects/tags';
import Users from './objects/users';
import VisitorActivities from './objects/visitor-activities';
import Visitors from './objects/visitors';
import Visits from './objects/visits';
export default class PardotClient {
    clientId: string;
    clientSecret: string;
    redirectUri: string;
    businessUnitId: string;
    baseUrl: string;
    apiVersion: number;
    refreshCallback?: RefreshCallback;
    oauthClient: AuthorizationCode;
    private accessToken?;
    private axiosInstance?;
    accounts: Accounts;
    campaigns: Campaigns;
    customFields: CustomFields;
    customRedirects: CustomRedirects;
    dynamicContent: DynamicContent;
    emails: Emails;
    emailClicks: EmailClicks;
    emailTemplates: EmailTemplates;
    forms: Forms;
    lifecycleHistories: LifecycleHistories;
    lifecycleStages: LifecycleStages;
    lists: Lists;
    listMemberships: ListMemberships;
    opportunities: Opportunities;
    prospects: Prospects;
    prospectAccounts: ProspectAccounts;
    tags: Tags;
    tagObjects: TagObjects;
    users: Users;
    visitors: Visitors;
    visitorActivities: VisitorActivities;
    visits: Visits;
    constructor({ clientId, clientSecret, redirectUri, token, businessUnitId, baseUrl, apiVersion, refreshCallback, }: PardotProps);
    authorizeUrl(props?: AuthorizeUrlProps): string;
    get token(): AccessToken;
    getAccessToken(code: string): Promise<RawAccessToken>;
    protected convertRequestValues(data: {
        [key: string]: unknown;
    }, isQueryRequest: boolean): {
        [key: string]: unknown;
    };
    get axios(): AxiosInstance;
    getApiUrl(object: string, pathParts: (string | number)[]): string;
}
